# ****************************************************************************
# "FIX8X14" - 8x14 font fixer (makefile)
#             Part of the 8x14 font fixing package "FIX8X14"
#
# Written by Robert Riebisch <rr@bttr-software.de>
# for BTTR Software
#
# Copyright (C) 1997-2002 BTTR Software
# [Under GNU GENERAL PUBLIC LICENSE]
# Published by BTTR Software
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
# ****************************************************************************

# Advanced SPHiNX C-- 0.237
CMMC = c--.exe
CMMCFLAGS =

# Netwide Assembler 0.98
ASM = nasm16.exe
ASMFLAGS =

COMPRESS = 1
# Ultimate Packer for eXecutables 1.20d
COMPRESSOR = upx.exe
COMPRESSORFLAGS = --best

all: diag8x14.com fix8x14.com fix8x14.sys

diag: diag8x14.com
tsr: fix8x14.com
sys: fix8x14.sys

clean:
  del diag8x14.com
  del fix8x14.com
  del fix8x14.sys

diag8x14.com:
  $(CMMC) diag8x14\diag8x14.c-- $(CMMCFLAGS)
  copy diag8x14\diag8x14.com *.*
  del diag8x14\diag8x14.com
  del warning

fix8x14.com:
  $(ASM) tsr\fix8x14.asm -o$< $(ASMFLAGS)
  !if $(COMPRESS)
    $(COMPRESSOR) $(COMPRESSORFLAGS) $<
  !endif

fix8x14.sys:
  $(ASM) sys\fix8x14.asm -o$< $(ASMFLAGS)
  !if $(COMPRESS)
    $(COMPRESSOR) $(COMPRESSORFLAGS) $<
  !endif
